language: node_js
node_js:
  - 6.11.2
sudo: required
services:
  - docker
env:
  global:
    - CXX=g++-4.8
  matrix:
    - USE_SENTRY=1
#    - USE_SENTRY=0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - docker pull getsentry/sentry-cli

script:
  - npm install
  - npm run build:dll
  - npm run build

before_deploy:
  - bash deploy/sentry_release.sh
  - find dist/ -type f -name "*.map" -delete
  - zip -r dist.zip dist

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: lrWZmJcGURa0S79Cld1vAYyEnY0Di98gbXL7vlDh7wpKBKeFwqDuIyhBQ2aYCBMKFb377r2CWxQ7OfPfquFHhB4TwrcFA8WLmbXbGTnzzg22Ojz2KMeu9FqyKA2L3UjYGpOkIDjT2s/o8W1DcvA71m7gQomNM4nMOPRbjZ0VBZB8U0nK0o9eTJFRGFoxCd99MXaRVLjT0A6cVEuu6bBpyQWRg165ULwK5HOPMRV2blGG4cExDTIQuLmWI9ZE7Dh1a1kmzkZi7nvjHC3YJU06tOxPTdpcFRuDb+84ZbIFaAQ6oh1aAunMknvtNCaN9LnvdcUq4Wjr6f6f6jnl78by2hha02xffmRwKwlaXYHMkgEiOZjcLlxjIYZuUysNy7nXu6smsHFoRIIQpJx9uhHymplMk6TIjzUXdNwrNJuP98nk+loP+IimRXoG1ErT3Cd65r4FWTViGdk0xc2Lx1aw2vCwQ5AcBTW3IYP/lZB+5YK8OsJucUugR5ayzKCFl+wSjS4JwP7XfQNYXzT+GCgdkhCbVQF4yitkv/PQYEUuvEcLwSC/WjYKkTWGey8ouFn+4XRKogf5vPlaMTDaUXZn/pP/ZtzjHb7ze1I5GUYUmKr9R5ov8PsJa1s1xYe6wPBed5NO8XM0osgrTlscL3O9+ZjCa6n8OgHBhXO8dORC8Ug=
  file: dist.zip
  on:
    repo: lvku/OnlineJudgeFE
    all_branches: true
    tags: true
